Bootstrap: docker

From: rocker/rstudio

%files
    init.sh /init.sh

%post
    echo "lock-type=linkbased" > /etc/rstudio/file-locks
    chmod 755 /init.sh
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    bash ~/miniconda.sh -b -p /opt/conda

    R --version

    echo "INSIDE CONTAINER BEING BUILT"

    # installing packages from cran
    R --slave -e 'install.packages("devtools",repos="https://cran.rstudio.com/")'
    R --slave -e 'install.packages("tidyverse",repos="https://cran.rstudio.com/")'


